### PR TITLE
Fix fname:: -> fname: (Remove extra colon)

### PR DESCRIPTION
**Pull request by MajorBreakfast**
I assume that colon snuck in there by accident.

### CODE REVIEW

**Comment by courtney-g** [comment]
+1

**Comment by 1ace** [comment]
There's an other one in [vkAllocateCommandBuffers.txt:28](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/man/vkAllocateCommandBuffers.txt#L28) :+1:

**Comment by MajorBreakfast** [comment]
@1ace Thx for spotting this.

I did a quick text search and these are all occurances of `fname::`.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.12 update. We're still sorting through some arcane issues around contributor license agreements, so rather than accepting the PR I did something equivalent internally - hopefully this will be resolved shortly

**Pull request closed without merging**
