### PR TITLE
Simplify links to external extensions

### PR DESCRIPTION
**Pull request by krOoze**
plus some collateral damage

### CODE REVIEW

**Comment by krOoze** [comment]
@oddhack Hm, why complicate things though... are you planning to preprocess the links or something? YAGNI

`link:` is the built-in, so probably taken. Would have to mess around in Ruby to figure out how not to break normal links. I am thinking maybe `registry:`?

**Comment by oddhack** [comment]
@krOoze I didn't mean to say the attribute names should be asciidoctor macros, just that they shouldn't claim the base extension name in this namespace. E.g. {link-GL_EXT_blah} would be OK. With that change we could accept this.

**Comment by krOoze** [comment]
@oddhack Hm, why though? The extensions are already namespaced by its prefix, and shouldn't otherwisely occur in the Vulkan spec.

The mangled name is awfully close to a macro. Do you have any esthetical preference before I start? `{link-GL_EXT_blah}` or `reglink:GL_EXT_blah` (or any other macro name that is not already taken).

BTW, if it was somewhat made consistent at what registry given GLSL extension is and if it has `GLSL` or `GL` prefix, then macro would be better and it would not require authors to manually add the links.

**Comment by oddhack** [comment]
I'd prefer link-extensionname. Changing the locations of files in the existing registries would be painful and require setting up rewrite directives in the webserver, which is not work I'm eager to do just to benefit this PR.

**Comment by krOoze** [comment]
That is not a prerequisite for the PR. It just means I would in the meantime still require the authors to manually add the GL links. On the other hand SPV (and others) does not seem to have such problem, so I could lift the requirement there.

Anyway I meant from purely esthetical standpoint. `{link-GL_EXT_blah}` makes it look macroish already, so maybe I could just as well just make it a real macro.

**Comment by krOoze** [comment]
Updated with the suggestion.

**Pull request closed without merging**
