### PR TITLE
Update VK_AMDX_shader_enqueue to v2

### PR DESCRIPTION
**Pull request by Tobski**
- Adds mesh shader node support
 - Adds two new limits to workgroups
 - Variable scratch size support

### CODE REVIEW

**Comment by Tobski** [comment]
From a quick look, it looks like the ash build is failing because it has old definitions for commands that were updated in this extension already in the crate, but would be good if we can find someone to check that...

**Comment by MarijnS95** [comment]
It looks like our hand-written "higher level" command wrappers for this extension are incompatible with the new signature, and would have to be updated via releasing the changes d regenerating + updating the `ash` crate.

However, I couldn't quickly find the right documentation on this but at least https://docs.vulkan.org/spec/latest/chapters/extensions.html#VkExtensionProperties says for the `specVersion` field (that's bumped from `1` to `2` here):

> `specVersion` is the version of this extension. It is an integer, incremented with backward compatible changes.

Is changing the function signature considered "backwards compatible"?

**Comment by oddhack** [comment]
> Is changing the function signature considered "backwards compatible"?

No. But this is an old vendor "experimental" extension (AMDX vendor ID), which is something like a "beta" extension is in current practice. That means that the API is not necessarily going to be stable.

**Comment by Tobski** [comment]
> > Is changing the function signature considered "backwards compatible"?
> 
> No. But this is an old vendor "experimental" extension (AMDX vendor ID), which is something like a "beta" extension is in current practice. That means that the API is not necessarily going to be stable.

Yea it's not meant to be stable, that's why it has the 'provisional="true"' attribute in the xml, as well as the AMDX tag. New revisions can just as well be entirely new extensions for provisional extensions. They're not generally available in consumer drivers, and are provided for developer feedback rather than productization.

**Review by oddhack — APPROVED** [review]
LGTM. Please tag Signed Off to Merge when you're ready (ideally today).

**Comment by Tobski** [comment]
> LGTM. Please tag Signed Off to Merge when you're ready (ideally today).
> 
> (Edit: and resolve conflicts, of course).

Done. Still failing Ash crate CI but @MarijnS95's PR should fix that once accepted.

**Comment by MarijnS95** [comment]
Thanks! We're doing the update in https://github.com/ash-rs/ash/pull/951, and attempting to prevent issues stemming from _allowed_ breaking changes to `provisional` extensions in https://github.com/ash-rs/ash/pull/952.

**Pull request merged**
