### PR TITLE
Add `VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR` to access masks VUIDs

### PR DESCRIPTION
**Pull request by Rua**
The bit was missing from these VUIDs, so this PR adds it.

### CODE REVIEW

**Review by Tobski — APPROVED** [review]
Looks good to me!

**Review by dgkoch — APPROVED** [review]
This seems to be more correct than what is there right now, but we might need to do some follow ups to clarify the meaning of the sync2 bits.

**Comment by oddhack** [comment]
> This seems to be more correct than what is there right now, but we might need to do some follow ups to clarify the meaning of the sync2 bits.

@dgkoch I'm interpreting that as a signoff - if not let me know by Wed. afternoon.

**Comment by dgkoch** [comment]
Yes - that was signoff to merge.

**Pull request merged**
