### PR TITLE
Separate reflow doc traversal and logic

### PR DESCRIPTION
**Pull request by ShabbyX**
The reflow code traversed asciidoc files and modified them.  The logic to traverse the files is split into its own class for future reuse.

### CODE REVIEW

**Comment by ShabbyX** [comment]
@oddhack this is preparation for the VU work. It separates the doc-traversal logic from the reflow/vuid logic. Later commits would use the doc-traversal logic for VU formatting.

You mentioned reflow.py is fragile, so I added some unit tests to make sure everything still works as expected, but do please give this a try. A good test would be running with this script on a commit before release and make sure the result is identical to the one that was fixed with the old reflow.py.

With the unit tests for reflow.py bootstrapped, it should be easy to add more tests as necessary.

**Comment by oddhack** [comment]
This seems fine - identical results to the old scripts run on the previous release and also some personal scripts I do strange transformations with. I think we can just mark this signed off as an editorial issue though will mention it on the teleconference today.

**Comment by oddhack** [comment]
BTW since you have developer access to this repo I'd find it helpful to put substantive PRs such as this as branches in the repo itself, which makes it easier to access them. Otherwise I'm left with again looking up the sequence of stuff to create a new remote in my clone, fetch a branch from it, etc. if I want to actually experiment with it.

**Comment by ShabbyX** [comment]
> BTW since you have developer access to this repo I'd find it helpful to put substantive PRs such as this as branches in the repo itself, which makes it easier to access them. Otherwise I'm left with again looking up the sequence of stuff to create a new remote in my clone, fetch a branch from it, etc. if I want to actually experiment with it.

Got it. I'll eventually move the other PRs to branches of this repo when time comes to move forward with them.

**Pull request merged**
