### PR TITLE
Add a new driver id VK_DRIVER_ID_MESA_VENUS

### PR DESCRIPTION
**Pull request by zhangyiwei**
@oddhack @olvaffe

### CODE REVIEW

**Comment by olvaffe** [comment]
LGTM

@anholt

**Comment by anholt** [comment]
LGTM

**Comment by zhangyiwei** [comment]
Hi Jon, friendly ping here for an update ; )

**Comment by oddhack** [comment]
> Hi Jon, friendly ping here for an update ; )

I'll merge this now, but we aren't going to be doing a spec update next week, so it will be a little while before it's published.

**Pull request merged**
