### PR TITLE
Generate a quick ref HTML page.

### PR DESCRIPTION
**Pull request by dj2**
This Cl adds a generator to create a quick_ref.html page which links to
the indvidual spec pages. The structure of the generated page is similar
to the vulkan quick reference document.

### CODE REVIEW

**Comment by dj2** [comment]
Does this seem like it would be generally useful? I find it's a lot easier to search in the page of just structs/enums and functions to find what I want and then got to the full page.

**Comment by oddhack** [comment]
Thanks for the suggestion - we can definitely stand to have some navigation. The index in man/apispec.txt is sort of this if it's changed from including the asciidoc refpages to linking to the target page, so I'm tempted to repurpose that (also, it's generated from the same process as the refpages, which guarantees that there won't be any dangling links). We'll take a closer look at this soon.

**Comment by dj2** [comment]
Does it generate an HTML version? I'm mostly looking for something I can use from the browser as I don't use the Vulkan man pages.

**Comment by dj2** [comment]
Going to close this as there doesn't seem to be interest.

**Pull request closed without merging**
