### PR TITLE
Add lunr to package.json

### PR DESCRIPTION
**Pull request by krOoze**
allows to simply `npm install` all deps

### CODE REVIEW

**Comment by oddhack** [comment]
TBH I'd like to remove this stuff. I don't know what its utility is and we very much want people to use our Docker image, or be completely responsible for their own build environment, at  this point.

**Comment by krOoze** [comment]
I believe it is something for the searchbox.

**Comment by oddhack** [comment]
The package* files, yes.

**Comment by krOoze** [comment]
Right. BTW I don't see where you are installing the `he` and `escape-string-regexp` in the docker. `package.json` could be still helpful to keep the dependencies organized even for the docker.

**Comment by oddhack** [comment]
> Right. BTW I don't see where you are installing the `he` and `escape-string-regexp` in the docker.

Thanks! I had forgotten to push the updated image / Dockerfile and was just running off the local cache without realizing it.

**Pull request merged**
