### PR TITLE
Fix optional bitmasks in non-optional array

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by oddhack** [comment]
Usual request, can we see the resulting changes in the generated VUs?

**Comment by krOoze** [comment]
@oddhack Right, it is supposed to be null diff with the `pBindingFlags` fix. Though something changed in newer commits. Hold on.

**Comment by krOoze** [comment]
@oddhack Conflict with 139 resolved. Diff:

diff

**Comment by oddhack** [comment]
@krooze is this MR still relevant? @jeffbolznv made a similar change in the 1.2.139 spec update and, AFAICT, the same validity comes out of your branch either at the 1.2.139 commit or the one following with your change.  Am I missing something?

**Comment by krOoze** [comment]
@oddhack I think so. I still get a diff matching the one posted above.

**Pull request merged**
